services:
  mysql-test:
    image: mysql:8.4.7@sha256:b306273d4d36bc1a7f265130c3dd93c0462253af7634203e569add0403a7b273
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconcile-account-topics
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
