services:
  mysql-test:
    image: mysql:8.4.8@sha256:7fcf7bcd3fa703ff23a2b998e4ed9077e5db570bcc4468459902e33b23d2841d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconcile-account-topics
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
