services:
  mysql-test:
    image: mysql:8.4.6@sha256:6e60ad6d61d8e7f0a4fd07f6b14109331d66a2f0d089e4b7a1f485d671a29604
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fix_reply_job
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
