services:
  mysql-test:
    image: mysql:8.4.7@sha256:5cdee9be17b6b7c804980be29d1bb0ba1536c7afaaed679fe0c1578ea0e3c233
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __JOB_NAME__
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
