services:
  mysql-test:
    image: mysql:8.4.8@sha256:f1c7674d8dd3c94f439b0d607792187d55bd861f94e8c6d683b959b577152bdc
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __JOB_NAME__
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
