services:
  mysql-test:
    image: mysql:8.4.6@sha256:5367102acfefeaa47eb0eb57c8d4f8b96c8c14004859131eac9bbfaa62f81e34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backfill-ghost-uuid
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
