name: Deploy

on:
  workflow_call:
    inputs:
      github-sha:
        description: Git Commit SHA
        required: true
        type: string

permissions:
  id-token: write

jobs:
  deploy-staging-migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [europe-west4]
        include:
          - region: europe-west4
            region_name: netherlands
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: projects/203831262197/locations/global/workloadIdentityPools/github-oidc-activitypub/providers/github-provider-activitypub
          service_account: stg-activitypub-terraform-cicd@ghost-activitypub-stg.iam.gserviceaccount.com

      - name: Deploy Migrations to Cloud Run
        if: ${{ matrix.region == 'europe-west4' }}
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          image: europe-docker.pkg.dev/ghost-activitypub/activitypub/migrations:${{ inputs.github-sha }}
          region: ${{ matrix.region }}
          job: stg-${{ matrix.region_name }}-activitypub-migrations
          flags: --wait --execute-now
          skip_default_labels: true
          labels: |-
            commit-sha=${{ github.sha }}

  deploy-staging-services:
    runs-on: ubuntu-latest
    needs: [deploy-staging-migrations]
    strategy:
      matrix:
        region: [europe-west4]
        service: [activitypub-queue, activitypub-retry-queue, activitypub-external, activitypub-api]
        include:
          - region: europe-west4
            region_name: netherlands
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: projects/203831262197/locations/global/workloadIdentityPools/github-oidc-activitypub/providers/github-provider-activitypub
          service_account: stg-activitypub-terraform-cicd@ghost-activitypub-stg.iam.gserviceaccount.com

      - name: Deploy ${{ matrix.service }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          image: europe-docker.pkg.dev/ghost-activitypub/activitypub/activitypub:${{ inputs.github-sha }}
          region: ${{ matrix.region }}
          service: stg-${{ matrix.region_name }}-${{ matrix.service }}
          skip_default_labels: true
          labels: |-
            commit-sha=${{ github.sha }}

  deploy-production-migrations:
    runs-on: ubuntu-latest
    needs: [deploy-staging-services]
    strategy:
      matrix:
        region: [europe-west4]
        include:
          - region: europe-west4
            region_name: netherlands
    steps:
      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: projects/687476608778/locations/global/workloadIdentityPools/github-oidc-activitypub/providers/github-provider-activitypub
          service_account: prd-activitypub-terraform-cicd@ghost-activitypub.iam.gserviceaccount.com

      - name: Deploy Migrations to Cloud Run
        if: ${{ matrix.region == 'europe-west4' }}
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          image: europe-docker.pkg.dev/ghost-activitypub/activitypub/migrations:${{ inputs.github-sha }}
          region: ${{ matrix.region }}
          job: prd-${{ matrix.region_name }}-activitypub-migrations
          flags: --wait --execute-now
          skip_default_labels: true
          labels: |-
            commit-sha=${{ github.sha }}

  deploy-production-services:
    runs-on: ubuntu-latest
    needs: [deploy-production-migrations]
    strategy:
      matrix:
        region: [europe-west4]
        service: [activitypub-queue, activitypub-retry-queue, activitypub-external, activitypub-api]
        include:
          - region: europe-west4
            region_name: netherlands
    steps:
      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: projects/687476608778/locations/global/workloadIdentityPools/github-oidc-activitypub/providers/github-provider-activitypub
          service_account: prd-activitypub-terraform-cicd@ghost-activitypub.iam.gserviceaccount.com

      - name: Deploy ${{ matrix.service }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          image: europe-docker.pkg.dev/ghost-activitypub/activitypub/activitypub:${{ inputs.github-sha }}
          region: ${{ matrix.region }}
          service: prd-${{ matrix.region_name }}-${{ matrix.service }}
          skip_default_labels: true
          labels: |-
            commit-sha=${{ github.sha }}
